[mypy]
strict = true
files = src/evalshift_cli
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
no_implicit_optional = true
disallow_any_generics = true
check_untyped_defs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_return_any = true
plugins = pydantic.mypy

[mypy-tests.*]
disallow_untyped_defs = false
disallow_incomplete_defs = false

[mypy-litellm]
ignore_missing_imports = true

[mypy-litellm.*]
ignore_missing_imports = true

[mypy-tiktoken]
ignore_missing_imports = true

[mypy-tiktoken.*]
ignore_missing_imports = true

[mypy-scipy.*]
ignore_missing_imports = true

[mypy-boto3]
ignore_missing_imports = true

[mypy-botocore.*]
ignore_missing_imports = true

[mypy-google.*]
ignore_missing_imports = true

[mypy-azure.*]
ignore_missing_imports = true

[pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
